name: ${project.name}
version: ${project.version}
description: ${project.description}
author: maciekmm
website: ${project.url}
main: ${main.class}
depend: [ProtocolLib]
commands:
  auracheck:
    description: Check if player has aura hack
    usage: /<command> <username> (invisible/visible) - checks for aura hack
    aliases: [ac]
    permission: auracheck.check
